bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'Ksh.100,000',
  '200000':'Ksh.200,000',
  '300000':'Ksh.300,000',
  '400000':'Ksh.400,000',
  '500000':'Ksh.500,000',
  '600000':'Ksh.600,000',
  '700000':'Ksh.700,000',
  '800000':'Ksh.800,000',
  '900000':'Ksh.900,000',
  '1000000':'Ksh.1M+',
}

state_choices = {
        'Ki': 'Kilimani',
        'Ka': 'Karen',
        'Ru': 'Runda',
        'Kile': 'Kileleshwa',
        'Mi': 'Milimani',
        'Ya': 'Yaya Center',
        'Ngo': 'Ngong',
        'Up': 'UpperHill',
        'Lavi': 'Lavington',
        'Wai': 'Waiyaki',
        'Wes': 'Westlands',
        'Bro': 'Brookside',
        'Kit': 'Kitusuru',
        'Muth': 'Muthaiga',
        'Gar': 'Garden City',
        'Ki': 'Kinoo',
        'Thik': 'Thika',
        'CBD': 'Central Business District',
        'Westy': 'Westlands',
        'Kili': 'Kilimani',
        'Lang': 'Langata',
        'Karen': 'Karen',
        'Kasa': 'Kasarani',
        'Eastleigh': 'Eastleigh',
        'Lavi': 'Lavington',
        'Ru': 'Runda',
        'Ngong Rd': 'Ngong Road',
        'Mutha': 'Muthaiga',
        'Buru': 'Buruburu',
        'Emba': 'Embakasi',
        'Parki': 'Parklands',
        'South C': 'South C',
        'South B': 'South B',
        'Hurlingham': 'Hurlingham',
        'Doni': 'Donholm',
        'Thika Road': 'Thika Road',
        'Kibera': 'Kibera',
        'Roysambu': 'Roysambu',
        'Ruaka': 'Ruaka',
        'Kahawa West': 'Kahawa West',
        'Utawala': 'Utawala',
        'Imara Daima': 'Imara Daima',
}